#ifndef NEOX_APPLET_SUPPORT_H
#define NEOX_APPLET_SUPPORT_H

#include <stdint.h>

#include <neox/applet.h>
#include <neox/types.h>

#define NEOX_APPLET_U32_DECIMAL_SIZE ((neox_size_t)10u)

/// <summary>
/// Returns the length of a NUL-terminated string.
/// </summary>
/// <param name="text">NUL-terminated string.</param>
/// <returns>Length excluding the terminating NUL byte.</returns>
neox_size_t neox_applet_string_length(const char* text);

/// <summary>
/// Writes a complete byte range, retrying partial writes.
/// </summary>
/// <param name="fd">Destination descriptor.</param>
/// <param name="buffer">Source byte range.</param>
/// <param name="length">Number of bytes to write.</param>
/// <returns>NEOX_STATUS_OK on success, otherwise the first write status.</returns>
neox_status_t neox_applet_write_all(
    neox_fd_t fd,
    const void* buffer,
    neox_size_t length);

/// <summary>
/// Writes one complete NUL-terminated string.
/// </summary>
/// <param name="fd">Destination descriptor.</param>
/// <param name="text">NUL-terminated string.</param>
/// <returns>NEOX_STATUS_OK on success, otherwise the first write status.</returns>
neox_status_t neox_applet_write_string(
    neox_fd_t fd,
    const char* text);

/// <summary>
/// Writes a diagnostic string to inherited stderr.
/// </summary>
/// <param name="text">NUL-terminated diagnostic string.</param>
void neox_applet_report(const char* text);

/// <summary>
/// Copies an argument span into a bounded NUL-terminated buffer.
/// </summary>
/// <param name="argument">Argument span to copy.</param>
/// <param name="buffer">Destination buffer.</param>
/// <param name="buffer_size">Destination capacity including NUL.</param>
/// <returns>NEOX_STATUS_OK on success, otherwise NEOX_STATUS_EINVAL.</returns>
neox_status_t neox_applet_copy_argument(
    const neox_arg_t* argument,
    char* buffer,
    neox_size_t buffer_size);

/// <summary>
/// Formats one unsigned 32-bit value as decimal ASCII.
/// </summary>
/// <param name="value">Value to format.</param>
/// <param name="buffer">Destination buffer with capacity 10 bytes.</param>
/// <returns>Number of generated bytes.</returns>
neox_size_t neox_applet_format_u32(
    uint32_t value,
    char* buffer);

/// <summary>
/// Formats one byte as two uppercase hexadecimal digits.
/// </summary>
/// <param name="value">Byte to format.</param>
/// <param name="buffer">Destination buffer with capacity 2 bytes.</param>
void neox_applet_format_hex8(
    uint8_t value,
    char* buffer);

#endif /* NEOX_APPLET_SUPPORT_H */
