#include <stdint.h>

#include <neox/applet_support.h>
#include <neox/io.h>
#include <neox/status.h>

static const char neox_applet_hex_digits[] = "0123456789ABCDEF";

/// <summary>
/// Returns the length of a NUL-terminated string.
/// </summary>
/// <param name="text">NUL-terminated string.</param>
/// <returns>Length excluding the terminating NUL byte.</returns>
neox_size_t neox_applet_string_length(const char* text)
{
    neox_size_t length;

    length = 0u;
    while (text[length] != '\0') {
        ++length;
    }

    return length;
}

/// <summary>
/// Writes a complete byte range, retrying partial writes.
/// </summary>
/// <param name="fd">Destination descriptor.</param>
/// <param name="buffer">Source byte range.</param>
/// <param name="length">Number of bytes to write.</param>
/// <returns>NEOX_STATUS_OK on success, otherwise the first write status.</returns>
neox_status_t neox_applet_write_all(
    neox_fd_t fd,
    const void* buffer,
    neox_size_t length)
{
    const uint8_t* current;
    neox_size_t remaining;

    current = (const uint8_t*)buffer;
    remaining = length;

    while (remaining != 0u) {
        neox_size_t written;
        neox_status_t status;

        written = 0u;
        status = neox_write(
            fd,
            current,
            remaining,
            &written);
        if (status != NEOX_STATUS_OK) {
            return status;
        }

        if (written == 0u) {
            return NEOX_STATUS_EIO;
        }

        current += written;
        remaining -= written;
    }

    return NEOX_STATUS_OK;
}

/// <summary>
/// Writes one complete NUL-terminated string.
/// </summary>
/// <param name="fd">Destination descriptor.</param>
/// <param name="text">NUL-terminated string.</param>
/// <returns>NEOX_STATUS_OK on success, otherwise the first write status.</returns>
neox_status_t neox_applet_write_string(
    neox_fd_t fd,
    const char* text)
{
    return neox_applet_write_all(
        fd,
        text,
        neox_applet_string_length(text));
}

/// <summary>
/// Writes a diagnostic string to inherited stderr.
/// </summary>
/// <param name="text">NUL-terminated diagnostic string.</param>
void neox_applet_report(const char* text)
{
    (void)neox_applet_write_string(
        NEOX_STDERR_FD,
        text);
}

/// <summary>
/// Copies an argument span into a bounded NUL-terminated buffer.
/// </summary>
/// <param name="argument">Argument span to copy.</param>
/// <param name="buffer">Destination buffer.</param>
/// <param name="buffer_size">Destination capacity including NUL.</param>
/// <returns>NEOX_STATUS_OK on success, otherwise NEOX_STATUS_EINVAL.</returns>
neox_status_t neox_applet_copy_argument(
    const neox_arg_t* argument,
    char* buffer,
    neox_size_t buffer_size)
{
    neox_size_t index;

    if (argument->length >= buffer_size) {
        return NEOX_STATUS_EINVAL;
    }

    for (index = 0u; index < argument->length; ++index) {
        buffer[index] = argument->data[index];
    }

    buffer[argument->length] = '\0';
    return NEOX_STATUS_OK;
}

/// <summary>
/// Formats one unsigned 32-bit value as decimal ASCII.
/// </summary>
/// <param name="value">Value to format.</param>
/// <param name="buffer">Destination buffer with capacity 10 bytes.</param>
/// <returns>Number of generated bytes.</returns>
neox_size_t neox_applet_format_u32(
    uint32_t value,
    char* buffer)
{
    char reverse[NEOX_APPLET_U32_DECIMAL_SIZE];
    neox_size_t count;
    neox_size_t index;

    count = 0u;

    do {
        reverse[count] = (char)('0' + (char)(value % 10u));
        ++count;
        value /= 10u;
    } while (value != 0u);

    for (index = 0u; index < count; ++index) {
        buffer[index] = reverse[count - index - 1u];
    }

    return count;
}

/// <summary>
/// Formats one byte as two uppercase hexadecimal digits.
/// </summary>
/// <param name="value">Byte to format.</param>
/// <param name="buffer">Destination buffer with capacity 2 bytes.</param>
void neox_applet_format_hex8(
    uint8_t value,
    char* buffer)
{
    buffer[0] = neox_applet_hex_digits[value >> 4];
    buffer[1] = neox_applet_hex_digits[value & 0x0Fu];
}
